# Generated by jPipe
# Source : justification/jd/deployable.jd
# Date   : 2026-06-29T09:24:53.215103500Z

from typing import Any, Callable
from jpipe_runner.framework.decorators.jpipe_decorator import jpipe
from jpipe_runner.framework.decorators.link_decorator import jpipe_link

JpipeProduce = Callable[[str, Any], None]

from pathlib import Path
import pandas as pd

HERE = Path(__file__).resolve().parent
PROJECT_ROOT = HERE.parent.parent

evidence_data = {
    "model_file" : "./model/model.pkl",
    "model_type" : "./model/model_type.txt",
    "x_test_file" : "./data/split/X_test.csv",
    "y_test_file" : "./data/split/y_test.csv",
    "p_test_file" : "./data/split/p_test.csv"
}

# Questions :
#
# Pourquoi les conclusions apparaissent dans le squelette de code ? 
# Dans quels cas on va avoir des test sur les conclusions ou sous conclusions, qui ne pourraient pas être déportés sur la stratégie qui les précède.
#
# Pourquoi la conclusion finale est la seule qui n'a pas le JpipeProduce en argument ?
#

@jpipe_link("deployable:assembleConclusion")
@jpipe(consume=['deployable'])
def model_is_deployable(deployable: bool) -> bool:
    """[conclusion] Model is deployable"""
    return deployable


@jpipe_link("deployable:fair:c")
@jpipe(produce=['fair'], consume=[])
def model_is_fair(produce: JpipeProduce) -> bool:
    """[sub-conclusion] Model is Fair"""
    produce('fair', True)
    return True


@jpipe_link("deployable:fair:dp_threshold")
@jpipe(produce=[], consume=['model_weights', 'model_type', 'X_test', 'y_test', 'p_test'])
def demographic_parity_difference_is_less_than_0_2(model_weights: str, model_type: str, 
                                                   X_test: str, y_test: str, p_test: str, 
                                                   produce: JpipeProduce) -> bool:
    """[strategy] Demographic Parity Difference is less than 0.2"""
    from src.models.utils import load_model
    from src.metrics.fairness import demographic_parity
    # load the model
    model = load_model(model_weights, model_type)
    # load the test data
    data = {}
    data["X_test"] = pd.read_csv(X_test)
    data["y_test"] = pd.read_csv(y_test)
    data["p_test"] = pd.read_csv(p_test)
    # predict y based on x_test
    data["y_pred"] = model.predict(X_test)
    # compute accuracy based on y_test and y_pred
    dp = demographic_parity(data)
    threshold = 0.2
    return dp < threshold


@jpipe_link("deployable:unified_0")
@jpipe(produce=['model_weights', 'model_type'])
def model_is_available(produce: JpipeProduce) -> bool:
    """[evidence] Model is available"""
    if (found_m := 'model_file' in evidence_data):
        produce('model_weights', evidence_data['model_file'])
    if (found_t := 'model_type' in evidence_data):
        produce('model_type', evidence_data['model_type'])
    return found_m and found_t


@jpipe_link("deployable:unified_1")
@jpipe(produce=['X_test', 'y_test', 'p_test'])
def test_dataset_is_available(produce: JpipeProduce) -> bool:
    """[evidence] Test dataset is available"""
    if (found_x := 'x_test_file' in evidence_data):
        produce('X_test', evidence_data['x_test_file'])
    if (found_y := 'y_test_file' in evidence_data):
        produce('y_test', evidence_data['y_test_file'])  
    if (found_p := 'p_test_file' in evidence_data):
        produce('p_test', evidence_data['p_test_file'])  
    return found_x and found_y and found_p


@jpipe_link("deployable:perf:c")
@jpipe(produce=['performant'], consume=[])
def model_is_performant(produce: JpipeProduce) -> bool:
    """[sub-conclusion] Model is Performant"""
    produce('performant', True)
    return True


@jpipe_link("deployable:perf:acc_threshold")
@jpipe(produce=[], consume=['model_weights', 'model_type', 'X_test', 'y_test'])
def accuracy_is_greater_than_0_8(model_weights: str, model_type: str, 
                                 X_test: str, y_test: str, 
                                 produce: JpipeProduce) -> bool:
    """[strategy] Accuracy is greater than 0.8"""
    from src.models.utils import load_model
    from src.metrics.predictive_perf import accuracy
    # load the model
    model = load_model(model_weights, model_type)
    # load the test data
    data = {}
    data["X_test"] = pd.read_csv(X_test)
    data["y_test"] = pd.read_csv(y_test)
    # predict y based on x_test
    data["y_pred"] = model.predict(X_test)
    # compute accuracy based on y_test and y_pred
    acc = accuracy(data)
    threshold = 0.8
    return acc > threshold


@jpipe_link("deployable:assembleStrategy")
@jpipe(produce=['deployable'], consume=['fair', 'performant'])
def all_conditions_are_met(fair: bool, performant: bool, 
                           produce: JpipeProduce) -> bool:
    """[strategy] All conditions are met"""
    if fair and performant :
        produce('deployable', True)
    return fair and performant


